### ISSUE TITLE
El carrito se desacomoda

### ISSUE THREAD

**Issue by rickypazd** [Casa-Grande/.github#23]
Hay q mejorar esta vista
![WhatsApp Image 2024-05-16 at 01 48 16](https://github.com/Casa-Grande/.github/assets/35882906/86f9921f-b959-4836-8934-8616a5bc045b)

**Comment by Licethd** [comment]
![image](https://github.com/Casa-Grande/.github/assets/72888760/9e9f71cb-9ba5-4366-97d6-44e7a196a66b)

**Comment by rickypazd** [comment]
To probe desde mi TECNO android  y dio.
