### ISSUE TITLE
Solo sale la alerta deberia enviar al login y luego volver.

### ISSUE THREAD

**Issue by rickypazd** [Casa-Grande/.github#24]
![WhatsApp Image 2024-05-16 at 01 48 26](https://github.com/Casa-Grande/.github/assets/35882906/f8d619f1-3332-4b0a-83ec-1b081620b772)

**Comment by Licethd** [comment]
probé con el loguin normal, solo que tarda un poco en redireccionar a carrito luego del logueo.
No puedo probar con loguin facebook y google
