### ISSUE TITLE
Crear un logo bonito y quisas cambiar la posocion al compartir

### ISSUE THREAD

**Issue by rickypazd** [Casa-Grande/.github#27]
<img width="660" alt="Screenshot 2024-05-17 at 00 45 02" src="https://github.com/Casa-Grande/.github/assets/35882906/4a9b94de-2baf-4793-b206-2ba48a453c9e">

**Comment by Licethd** [comment]
![image](https://github.com/Casa-Grande/.github/assets/72888760/26e50616-0e5c-446d-8ec0-d89f28ee83e6)
